import type { TeamProfile } from './types';

export const MOCK_TEAMS: TeamProfile[] = [
  {
    id: 'cp-tri',
    slug: 'cal-poly-triathlon',
    name: 'Cal Poly Triathlon',
    university: 'Cal Poly San Luis Obispo',
    sport: 'Triathlon',
    location: 'San Luis Obispo, CA',
    rosterSize: 80,
    yearFounded: 2005,
    oneLiner:
      "Cal Poly's largest club sport — 80 athletes competing at collegiate nationals and hosting the March Triathlon Series",
    description:
      '80+ athletes split across draft-legal, long course, and Olympic distances. We host the annual March Triathlon Series (MTS) every spring with 500+ athletes and travel to USAT Collegiate Nationals. Strong sponsor-fulfillment track record with 10 product brands over the last 3 seasons.',
    league: 'USA Triathlon Collegiate',
    competitionSummary:
      'West Regional Championships (April), USAT Collegiate Nationals (April), March Triathlon Series — host (March)',
    season: 'Year-round',
    websiteUrl: 'https://calpolytriathlon.com',
    instagramUrl: 'https://instagram.com/calpolytriathlon',
    tiktokUrl: 'https://tiktok.com/@calpolytri',
    combinedReach: 8000,
    socialLinks: [
      { platform: 'Instagram', url: 'https://instagram.com/calpolytriathlon', followerCount: 3200 },
      { platform: 'TikTok', url: 'https://tiktok.com/@calpolytri', followerCount: 1800 },
      { platform: 'Newsletter', url: '', followerCount: 640 },
    ],
    events: [
      {
        id: 'evt-1',
        name: 'West Regional Championships',
        eventType: 'competition',
        startsOn: '2026-04-11',
        location: 'Tempe, AZ',
        expectedAttendance: 300,
      },
      {
        id: 'evt-2',
        name: 'USAT Collegiate Nationals',
        eventType: 'competition',
        startsOn: '2026-04-25',
        location: 'Tempe, AZ',
        expectedAttendance: 2000,
      },
    ],
    hostedEvents: [
      {
        id: 'hosted-1',
        name: 'March Triathlon Series (MTS)',
        eventType: 'hosted_event',
        startsOn: '2026-03-07',
        location: 'San Luis Obispo, CA',
        expectedAttendance: 500,
        notes:
          'Sprint + Olympic distances. Packet pickup, finish-line booths, podium awards, and post-race expo all open to sponsors.',
      },
    ],
    sponsorshipAssets: [
      { assetId: 'jersey_logo', status: 'preferred', notes: 'Preferred — strongest visibility' },
      { assetId: 'brand_booth', status: 'preferred', notes: 'Available at MTS and home events' },
      { assetId: 'product_sampling', status: 'available', notes: 'On-course nutrition at MTS' },
      { assetId: 'athlete_packet_stuffing', status: 'available' },
      { assetId: 'podium_prize_sponsorship', status: 'available' },
      { assetId: 'packet_pickup_hosting', status: 'available' },
      { assetId: 'instagram_post', status: 'available' },
      { assetId: 'instagram_story', status: 'available' },
      { assetId: 'banner_at_games', status: 'available' },
      { assetId: 'website_logo', status: 'available' },
    ],
    preferredSponsorCategories: ['Nutrition', 'Beverage', 'Apparel', 'Equipment', 'Recovery/Fitness'],
    excludedSponsorCategories: ['Alcohol', 'Gambling', 'Tobacco/Nicotine'],
    dealTypesInterestedIn: [
      'Free product for team use',
      'Cash sponsorship',
      'Event prizes',
      'Product for event packets/goody bags',
      'On-site services',
    ],
    verificationStatus: 'verified',
    profileCompleteness: 92,
    photo: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=1200&q=70',
    pastSponsors: [
      'Sailfish',
      'Garmin',
      'Fluid Nutrition',
      '100%',
      'Carbs Fuel',
      'Voler',
      'Running Warehouse',
      'GH Sports',
      'Cambria Bike',
      'Maurten',
    ],
  },
  {
    id: 'cp-soccer',
    slug: 'cal-poly-mens-soccer',
    name: "Cal Poly Men's Soccer",
    university: 'Cal Poly San Luis Obispo',
    sport: 'Soccer',
    location: 'San Luis Obispo, CA',
    rosterSize: 50,
    yearFounded: 1998,
    oneLiner:
      'Division I club soccer competing in the WCSA with 100K+ highlight views per season',
    description:
      'Top-ranked NIRSA Region VI club. Weekly livestreams on Veo, regular highlight reels, and an active social audience. We compete in the West Coast Soccer Association with home matches at Mustang Field. Looking for sponsors who want high-visibility digital placements rather than traditional jersey logos.',
    league: 'West Coast Soccer Association',
    competitionSummary:
      'WCSA regular season (Fall), NIRSA Regional Championship (November), NIRSA National Championship qualifier',
    season: 'Fall',
    websiteUrl: 'https://calpoly.campuslabs.com/engage/organization/menssoccer',
    instagramUrl: 'https://instagram.com/cpmenssoccer',
    livestreamUrl: 'https://veo.co/calpolymenssoccer',
    combinedReach: 12000,
    socialLinks: [
      { platform: 'Instagram', url: 'https://instagram.com/cpmenssoccer', followerCount: 2100 },
      { platform: 'Veo Livestream', url: 'https://veo.co/calpolymenssoccer', followerCount: 8400 },
      { platform: 'TikTok', url: 'https://tiktok.com/@cpmenssoccer', followerCount: 1500 },
    ],
    events: [
      {
        id: 'evt-3',
        name: 'WCSA Fall Season',
        eventType: 'competition',
        startsOn: '2026-09-05',
        location: 'San Luis Obispo, CA',
        expectedAttendance: 200,
        notes: '10 home matches, weekly livestreams',
      },
      {
        id: 'evt-4',
        name: 'NIRSA Region VI Championship',
        eventType: 'competition',
        startsOn: '2026-11-14',
        location: 'TBD',
        expectedAttendance: 500,
      },
    ],
    hostedEvents: [],
    sponsorshipAssets: [
      { assetId: 'livestream_ad_placement', status: 'preferred', notes: 'Pre-roll + banner overlay on Veo streams' },
      { assetId: 'highlight_video_logo', status: 'preferred', notes: '100K+ views per season' },
      { assetId: 'instagram_post', status: 'available' },
      { assetId: 'instagram_story', status: 'available' },
      { assetId: 'tiktok_reel', status: 'available' },
      { assetId: 'banner_at_games', status: 'available', notes: 'Sideline banners at Mustang Field' },
      { assetId: 'jersey_logo', status: 'unavailable', notes: 'We prefer to keep jerseys clean' },
    ],
    preferredSponsorCategories: ['Beverage', 'Apparel', 'Equipment', 'Technology', 'Local Business'],
    excludedSponsorCategories: ['Energy Drinks', 'Alcohol', 'Gambling'],
    dealTypesInterestedIn: [
      'Free product for team use',
      'Cash sponsorship',
      'Discount codes',
      'Gift cards',
    ],
    verificationStatus: 'draft',
    profileCompleteness: 68,
    photo: 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=1200&q=70',
    pastSponsors: [],
  },
  {
    id: 'cp-rugby',
    slug: 'cal-poly-mens-rugby',
    name: "Cal Poly Men's Rugby",
    university: 'Cal Poly San Luis Obispo',
    sport: 'Rugby',
    location: 'San Luis Obispo, CA',
    rosterSize: 45,
    yearFounded: 1970,
    oneLiner: 'D1A club rugby program with loyal sideline crowds and an active alumni network',
    description:
      'D1A club rugby competing in the Pacific Western Rugby Conference. Home matches at Mustang Field draw consistent sideline crowds. Strong alumni donor base and local business partnerships.',
    league: 'Pacific Western Rugby Conference',
    season: 'Spring',
    combinedReach: 4200,
    socialLinks: [
      { platform: 'Instagram', url: 'https://instagram.com/cpmenrugby', followerCount: 3200 },
      { platform: 'TikTok', url: '', followerCount: 1000 },
    ],
    events: [],
    hostedEvents: [],
    sponsorshipAssets: [
      { assetId: 'jersey_logo', status: 'preferred' },
      { assetId: 'banner_at_games', status: 'available' },
      { assetId: 'instagram_post', status: 'available' },
      { assetId: 'instagram_story', status: 'available' },
    ],
    preferredSponsorCategories: ['Apparel', 'Beverage', 'Local Business', 'Recovery/Fitness'],
    excludedSponsorCategories: ['Gambling'],
    dealTypesInterestedIn: ['Cash sponsorship', 'Free product for team use', 'Discount codes'],
    verificationStatus: 'verified',
    profileCompleteness: 55,
    photo: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=70',
    pastSponsors: ['Rhino Rugby', 'SLO Brew', 'Central Coast Physical Therapy', 'Firestone Grill'],
  },
  {
    id: 'cp-swim',
    slug: 'cal-poly-club-swim',
    name: 'Cal Poly Club Swim',
    university: 'Cal Poly San Luis Obispo',
    sport: 'Swim',
    location: 'San Luis Obispo, CA',
    rosterSize: 40,
    yearFounded: 2010,
    oneLiner: 'Nationally competitive club swim with 20+ past product collaborations',
    description:
      'Travels to CSCA Nationals every spring. 20+ past product sponsors over the last 4 seasons. Great for sampling and gear — we have a captive audience of 40 athletes who train daily.',
    league: 'College Swimming Club Association',
    season: 'Fall & Spring',
    combinedReach: 3200,
    socialLinks: [
      { platform: 'Instagram', url: 'https://instagram.com/cpclubswim', followerCount: 2600 },
    ],
    events: [
      {
        id: 'evt-5',
        name: 'CSCA Nationals',
        eventType: 'competition',
        startsOn: '2026-04-03',
        location: 'Atlanta, GA',
        expectedAttendance: 1500,
      },
    ],
    hostedEvents: [],
    sponsorshipAssets: [
      { assetId: 'instagram_post', status: 'preferred' },
      { assetId: 'instagram_story', status: 'available' },
      { assetId: 'product_sampling', status: 'preferred', notes: 'Captive audience of 40 daily athletes' },
    ],
    preferredSponsorCategories: ['Apparel', 'Nutrition', 'Recovery/Fitness', 'Equipment'],
    excludedSponsorCategories: ['Supplements we cannot verify', 'Tobacco/Nicotine'],
    dealTypesInterestedIn: ['Free product for team use', 'Discount codes', 'Gift cards'],
    verificationStatus: 'verified',
    profileCompleteness: 60,
    photo: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?auto=format&fit=crop&w=1200&q=70',
    pastSponsors: [
      'TYR',
      'Speedo',
      'Arena',
      'SwimOutlet',
      'FINIS',
      'Roka',
      'Skratch Labs',
    ],
  },
];

export function getTeamBySlug(slug: string): TeamProfile | undefined {
  return MOCK_TEAMS.find((t) => t.slug === slug);
}
