exclude_path = [
  ".git",
  "node_modules",
]

exclude = [
  "http://localhost:*",
  "https://localhost:*"
]

max_retries = 2
timeout = 20
accept = [200, 206, 429]

[markdown]
# Enable link checking in markdown files
enabled = true
