blank_issues_enabled: false
contact_links:
  - name: Spontus HQ in Notion
    url: https://www.notion.so/a13ae01f89cf82adafb101ea94d6d1ab?pvs=1
    about: Use the Notion HQ for strategy, research synthesis, and operating context.
